### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [gjedeer/mylocation#12]
Hi @gjedeer 

I found [this app](https://play.google.com/store/apps/details?id=net.tworams.mobile.myposition) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v2 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide a link to this repo, screenshots of your app and screenshots of the fake app.

**Comment by gjedeer** [comment]
@Poussinou as https://github.com/gjedeer/mylocation#license clearly states, this is a fork of an unmaintained app and I'm not the original author. I'm not sure if it's still okay for me to send a removal request.

@spidero installed that app and sent me a screen shot.

![screenshot_2017-09-28-08-27-29](https://user-images.githubusercontent.com/315648/30953755-9252dda0-a42d-11e7-8ee0-0057872572ac.png)

**Comment by Poussinou** [comment]
I don't know if this fake app is based on your own code or the old version of mypapit. What do you think about this question? If it's based on your own version, you're allowed to fill a takedown request because a part of the code belongs to you.

**Comment by gjedeer** [comment]
The original version didn't have links to maps so it's likely based on mine. Thanks for the advice.

**Comment by gjedeer** [comment]
Just a follow up: I contacted Google, they started making it difficult, I gave up because I don't care enough. Closing this issue: wontfix.

**Comment by gjedeer** [comment]
And in the spirit of openness: by "making it difficult" I mean asking to send a screenshot with infringing content again and again. Frankly, I didn't even have patience to get through my cable internet company's support stupidness when they took away my public IPv4 - a thing which actually affected my life - and infringement of a minor program developed in free time is much lower on the list of my priorities.

**Comment by Poussinou** [comment]
I understand this, thanks for trying !

By the way, this is not the first time a developer like you report that it's very difficult to takedown a copied app...

Again, thanks
