### ISSUE TITLE
App shows wrong location 

### ISSUE THREAD

**Issue by Olamatto** [gjedeer/mylocation#18]
#### Expected behavior
The application is expected to show correct location of user.

#### Actual Behavior 
The application shows wrong location.

#### How to reproduce
- Download and install the application [here](https://f-droid.org/repository/browse/?fdcategory=Navigation&fdid=net.mypapit.mobile.myposition&fdpage=3)

#### To enable app run smoothly 
- Go to Settings -> Apps -> My Position -> Permissions
- Enable location on phone
<hr>

- Lunch the application 
- wait for it to get your location
- And see it is a wrong location
- Click on Get fix
- Then another wrong location shows up
<hr>

Application version: v 1.3.0
Operating system: Android v7.0

#### Recording Of The Bug
https://cdn.steemitimages.com/DQmfC7ampBwLjQmGUwyJjH8vJFPdjYce3QEjSKw3vHKjs25/videotogif_2018.05.27_04.34.15.gif

**Comment by gjedeer** [comment]
Thank you for your report.

Do you mean that the coordinates are wrong or is it about the "Location" section with address?

"Location" is guessed using your Network Location Provider, this app is just displaying it. For most phones, it's Google Maps that's providing this data. For NOGAPPS phones phones it's the UnifiedNLP app that provides it (and it takes data from OpenStreetMaps).

On Google Apps there's an easy way to check if Google knows the right address for your location: https://f.gdr.name/googlelocation-2018-05-27_07.49.23.mp4

**Comment by gjedeer** [comment]
Looks like Google has the wrong data for your location:

https://f.gdr.name/googlelocation2-2018-05-27_08.40.17.mp4

Out of curiosity, I checked on OpenStreetMap.org and it's displaying "Ogbo, Odogbolu, Ogun, Nigeria" - the same as Google.
