### ISSUE TITLE
Logo proposal for My Location

### ISSUE THREAD

**Issue by ahyar92** [gjedeer/mylocation#19]
Hi sir, If you still remember it, I've reported a bug before. At this time, I would like to offer a logo for your application. I am designing this logo to give the latest impression to your application. Here's a logo idea for you:
![11.png](https://cdn.steemitimages.com/DQmZKJdqX5UGfiqXeSL2d4SoQxsaHquzkU5d3hfTczJWs2n/11.png)

I am new to github, I do not know how to add pull request, if you are interested I will send some files in GOOGLE DRIVE for you sir :)

I will wait your reply :)

Thanks You

**Comment by gjedeer** [comment]
Hello, that's a nice logo! Thank you.

Do you think you can also make variations of the logo as described here? https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive 

I'll use the icon if you don't do it - but it would be nice to have Android 8 compatible icon too.

If you don't do a pull request that's OK but I need you to add a comment like "I, ahyar92, hereby release these icons under a GPL license version 2" with your Google Drive link. Just to have 100% legal Free Software licensing.

Anyway: thanks and a nice surprise for a Monday morning! :)

**Comment by ahyar92** [comment]
I'm sorry, I still do not understand what you want. However, I can provide background variations for icons. Give me a few minutes to upload it on Google drive. Next I will reply this as you ordered.

BTW, I'm so happy you like it :)

**Comment by ahyar92** [comment]
I ahyar92, hereby release these icons under the GPL version 2 license
https://drive.google.com/open?id=1seXevweaB6edkwpMbXxzwQVQ-NWJWvUn

**Comment by gjedeer** [comment]
To be honest I didn't study the Android 8 icon requirements myself, I
just know Google has some new requirements. The link I sent was in fact
not very descriptive...

Here's some video I've found about how to design such icons:
https://www.youtube.com/watch?v=tidxhJNUPSE
Only if you think it's a fun thing to do with your time :)

**Comment by ahyar92** [comment]
Thanks for the video instructions you submitted, it may take a few days for me to master it. And I really like new things. :)
Are you going to keep using icons from me sir @gjedeer  :) ?

**Comment by gjedeer** [comment]
https://fb.gdr.name/app-debug.apk if you want to see how it looks. Next release will have your icon.

**Comment by ahyar92** [comment]
Thank you very much sir, I am very happy to hear it :).
If in the future you need a logo again. Just contact me, I will design for free for you.

**Comment by gjedeer** [comment]
@ahyar92 it took me a little time, but version 1.3.3 will be on F-Droid any day now. Thank you again for the new logo, it looks so much better.
