### ISSUE TITLE
State license in readme or seperate LICENSE file

### ISSUE THREAD

**Issue by ghost** [gjedeer/mylocation#2]
State license in readme or seperate LICENSE file. The GoogleCode project says GPLv2, but github doesn't show a licene. Also, GPLv2 is incompatible with the Apache2 license used in the support libraries. I'd recommend to switch to GPLv2+ (GPLv2 with the "and later versions" addition).

**Comment by gjedeer** [comment]
License added, I'm not sure what to do about incompatibility. Is there any point trying to add it to fdroid, or is this not fixable?

**Comment by ghost** [comment]
With the addition of "and later versions" the license should be okay. In fact, I just pushed the metadata to fdroid (most likely just a little to late for tonights build job, so it should be published in 1-2 days).
