### ISSUE TITLE
Copy location to clipboard

### ISSUE THREAD

**Issue by rerobins** [gjedeer/mylocation#20]
Please add feature to copy the location to the clipboard instead of sharing with another application.  Would also be nice to specify what is copied:

- geo uri
- Google Maps URL
- or open street map URL

**Comment by gjedeer** [comment]
Every Android phone I owned except for the G1 had the option "copy to
clipboard" in the Share menu.

As to specifying what to copy, I may one day add a setting to disable
generating certain links.

**Comment by rerobins** [comment]
It doesn't appear in my share menu because I don't have google drive installed.  

See: https://www.reddit.com/r/AndroidQuestions/comments/68fus4/how_to_add_copy_to_clipboard_option_in_android/

**Comment by gjedeer** [comment]
I don't have Google Drive either, gapps-free since 2013 or so. Maybe
it's a LineageOS feature and you're using some other build.

If you don't have it, then maybe try "share to clipboard" app on
F-Droid?

**Comment by rerobins** [comment]
Not a LOS feature, I'm on 14.1 will check out the app you mentioned.

**Comment by CodeCubeNeo** [comment]
Any updates on this?

**Comment by gjedeer** [comment]
I don't have any need for this, especially with Android 13+ where copy and share are even more tightly integrated. But I'd merge a pull request if someone who needs this adds this feature.
