### ISSUE TITLE
Trigger by text message or email

### ISSUE THREAD

**Issue by Markus00000** [gjedeer/mylocation#21]
Location sharing could be triggered if an incoming text message or email contains a certain string. The app would then automatically reply with the current location.

Why?

1. Give trusted persons the ability to locate you, especially in case of emergencies.
2. Locating a misplaced or stolen phone.

([FindMyPhone](https://erikofsweden.blogspot.com/p/findmyphone.html) implemented this partially. Same issue for Location Share at https://github.com/pR0Ps/LocationShare/issues/34.)

**Comment by gjedeer** [comment]
Sorry, no plans to implement it.
