### ISSUE TITLE
Add OLC aka Plus Code support

### ISSUE THREAD

**Issue by goblin** [gjedeer/mylocation#22]
[Plus Codes](https://plus.codes/) aka [Open Location Codes](https://en.wikipedia.org/wiki/Open_Location_Code) are the fresh and hot new invention from Google.

I'm gonna have a try at it now, see if I can make a PR out of it.

I'm thinking to create a new section below decimal and degree coordinates to display and be able to share the code, as well as adding this section to the converter.

**Comment by gjedeer** [comment]
Sounds like a good idea, why not! Interesting that they did not come up with an URL scheme too (pluscode:ABC123) but nevertheless: PR would be very welcome
