### ISSUE TITLE
Adjusted text for all links

### ISSUE THREAD

**Issue by bege10** [gjedeer/mylocation#32]
I can adjust the text for the message. Please, use that text also for sharing the other values. Thanks.

**Comment by gjedeer** [comment]
Not sure what you mean here.

**Comment by bege10** [comment]
One can set a custom text for sharing ones location. But that text is only used for sharing "Message", not for the other 4 values (Location, Coordinates and Open Location Code).

**Comment by gjedeer** [comment]
Oh, that's by design.

**Comment by bege10** [comment]
> Oh, that's by design.

I hoped you could/would change that.

**Comment by gjedeer** [comment]
I like the ability to share just links. Sorry.
