### ISSUE TITLE
GPS constantly used

### ISSUE THREAD

**Issue by tbo47** [gjedeer/mylocation#4]
When the app is in background it still constantly use the GPS. It is using a lot of battery for no reason.

**Comment by gjedeer** [comment]
In background? 

As in, when you hit the home screen you still see the app running and checking GPS?

**Comment by gjedeer** [comment]
I just pushed the cleanup I did some time ago to master - if you could build that and check if it solves your problem.

The gps code was really crappy in the original version before fork - and i released that because it somehow worked. Now I got rid of the unnecessary extra thread and there should be less surprises.

**Comment by gjedeer** [comment]
Reopen if the issue persists.

**Comment by spaetz** [comment]
Hi, using version 1.2.4 from fdroid. GPS is constantly used when I return to the Homescreen. When I explicitely close the app (wipe it from the app overview screen) the GPS symbol disappears immediately. So this seems to not be fixed yet.
Thanks for the app!

**Comment by gjedeer** [comment]
Perhaps we need to capture the "lost focus" event and stop receiving
GPS notifications then?

Anyway, this is not happening here so if I get to fixing that, I'll ask
you to check.

**Comment by Lee-Carre** [comment]
Use the `passive` location provider?

**Comment by gjedeer** [comment]
@Lee-Carre no, that will not work, the passive location provider often returns stale data and claims it's fresh. That's okay for most uses but in this case, I want to make sure that when the app says location is 1 second old, it's 1 second old.
