### ISSUE TITLE
Decimal point in spanish android

### ISSUE THREAD

**Issue by escobrice** [gjedeer/mylocation#6]
Both "Decimal Coordinate", "Degree Coordinate" and "geo:" are misformat in spanish and when you try to use it, it doesn't work
MyLocation says:
geo:36,68269,-6,131162;u=9
should say:
geo:36.68269,-6.131162;u=9
I think it's a regional decimal separator trouble

**Comment by gjedeer** [comment]
Hi,

Are you on version 1.2.2? There was a fix for your issue:

https://github.com/gjedeer/mylocation/pull/5

**Comment by escobrice** [comment]
I install Mylocation from f-droid and last version is 1.2.1

2016-05-02 8:47 GMT+02:00 GDR! notifications@github.com:

> Hi,
> 
> Are you on version 1.2.2? There was a fix for your issue:
> 
> https://github.com/gjedeer/mylocation/pull/5
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gjedeer/mylocation/issues/6#issuecomment-216117716

## 

chau!
Carlos

http://www.escobrice.net

**Comment by gjedeer** [comment]
1.2.2 should be in F-Droid any time now. Please reopen this issue if your problem persists in 1.2.2 from F-Droid.

**Comment by gjedeer** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/1396#note_11646289
